##### [Full list of numpy functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html): 
##### [Tutorial](http://cs231n.github.io/python-numpy-tutorial/)

In [1]:
import numpy as np

a = np.array([1,2,3])

In [2]:
print(type(a))

<type 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
a[1]

2

In [5]:
b = np.array([ [1,2,3], [4,5,6]])

In [6]:
print(b.shape)

(2, 3)


In [7]:
print(b[0,0], b[0,1])

(1, 2)


In [8]:
a = np.zeros((2,2))

In [9]:
a

array([[0., 0.],
       [0., 0.]])

In [10]:
a = np.ones((1,2))

In [11]:
a

array([[1., 1.]])

In [12]:
a = np.ones((2,2))

In [13]:
a

array([[1., 1.],
       [1., 1.]])

In [16]:
a = np.eye((2))
print(a)

[[1. 0.]
 [0. 1.]]


In [17]:
a = np.random.random((2,2)) # np array filled with random values
print(a)

[[0.4260372  0.08774976]
 [0.45814924 0.53534104]]


#### INDEXING

In [25]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use SLICING to pull out the subarray consisting of the first two rows
# and columns 1 and 2;


In [29]:
b=a[:2,1:3]

In [30]:
# The slice of an array is a view into the same data, so modifying it 
# Will modify the original array
print(a[0,1])

2


In [31]:
b[0,0] = 77 # b[0, 0] is the same piece of data as a[0, 1]

In [32]:
print(a[0,1])

77


In [33]:
a[1,:]

array([5, 6, 7, 8])

In [34]:
a[:,2]

array([ 3,  7, 11])

In [35]:
a[1:2,:] # get only second row

array([[5, 6, 7, 8]])

In [36]:
row_1 = a[1:2,:] 

In [37]:
print(row_1, row_1.shape)

(array([[5, 6, 7, 8]]), (1, 4))


In [38]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

(array([77,  6, 10]), (3,))
(array([[77],
       [ 6],
       [10]]), (3, 1))


In [53]:
"""
    While indexing np arrays using slicing gives a subarray of the original
    one, integer array indexing allows creating any array 
    using data from the original one;
"""
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[1 4 5]


In [54]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"


[1 4 5]


In [56]:
a = np.array([[1,2], [3, 4], [5, 6]])


In [57]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
a[[0,1,2],[0,1,0]] 
# The returned array will have shape (3,) and

array([1, 4, 5])

In [64]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]


In [62]:
a[[0,1],[0,1]]

array([1, 4])

In [65]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

[2 2]


In [66]:
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"


[2 2]


In [67]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [69]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
b = np.array([0, 2, 0, 1])

In [73]:
a[np.arange(4), b] # <=> a[ [0,1,2,3], [0,2,0,1] ] = [1, 6, 7, 11]

array([ 1,  6,  7, 11])

In [74]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

In [75]:
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [76]:
# Boolean array indexing
a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (a > 2) 

In [77]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [78]:
# Construct a rank 1 array (1D array) consisting of the elements
# of a corresponding True value of bool_idx
print(a[bool_idx])

[3 4 5 6]


In [79]:
print(a[a>2])

[3 4 5 6]


In [80]:
# Datatypes
x = np.array([1,2])
print(x.dtype)

int64


In [81]:
# Numpy determines the datatype itself
x = np.array([1.0, 2.0])
print(x.dtype)

float64


In [82]:
x = np.array([1,2], dtype=np.int64)
print(x.dtype)

int64


In [85]:
"""
    ARRAY MATH:
    
    Basic math functions operate elementwise on arrays, and are 
    available both as operator overloads and as functions in the 
    numpy module:
"""
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

In [86]:
x

array([[1., 2.],
       [3., 4.]])

In [87]:
# Elementwise sum; 
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [88]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [89]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [90]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [97]:
print(x * y) # "*" is elementwise multiplication not dot function
# to compute inner products of vectors, to multiply a vector by a matrix, 
# and to multiply matrices. "dot" is available as both a function 
# in the numpy module, and as an instance method of array objects

[[ 5. 12.]
 [21. 32.]]


In [98]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [99]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [100]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [101]:
print(np.sqrt(x)) # Elementwise square root

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [102]:
x = np.array([[1,2],[3,4]])

In [103]:
y = np.array([[5,6], [7,8]])

In [104]:
v = np.array([9,10])

In [105]:
w = np.array([11,12])

In [106]:
print(v.dot(w))

219


In [108]:
# Matrix - vector product; produce 1 rank array [29 67]
print(np.dot(x,v))

[29 67]


In [109]:
aa=np.array([[5,6],[8,10]])
bb=np.array([2,3])
aa.dot(bb)

array([28, 46])

In [110]:
print(np.sum(x))

10


In [111]:
# sum of each column
print(np.sum(x, axis=0))

[4 6]


In [112]:
# sum of each row
print(np.sum(x, axis=1))

[3 7]


In [113]:
# Transpose
print(x.T)

[[1 3]
 [2 4]]


In [114]:
print(x[0:1, 1])

[2]


In [115]:
print(x)

[[1 2]
 [3 4]]


In [116]:
print(x[0:1, 0])

[1]


In [117]:
X = []

In [118]:
X.append(x)

In [119]:
X

[array([[1, 2],
        [3, 4]])]

In [20]:
import numpy as np
""" 
Veprimet matricore ne rrjeta neurale
"""

a = np.array([[1,2,3], [1,2,3]])
b = np.array([[1,1], [2,2], [3,3]])

c = np.array([[4,5,6], [4,5,6]])
d = np.array([[4,5,6], [4,5,6]])

print ( "Prodhimi element-per-element i Hadamar-it: \n" +
       str(c*d) + 
       "\n")
print( "Dot product: " + str(np.dot(a,b)))

Prodhimi element-per-element i Hadamar-it: 
[[16 25 36]
 [16 25 36]]

Dot product: [[14 14]
 [14 14]]


In [7]:
np.dot(a,b)

array([[14, 14],
       [14, 14]])

In [1]:
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)

# line, = ax.plot(x1, x2, lw=2)

# ax.annotate('local max', xy=(2, 1), xytext=(3, 1.5),
#             arrowprops=dict(facecolor='black', shrink=0.05),
#             )

ax.set_ylim(0,1.75)
ax.set_xlim(0,1.75)

# plt.scatter([0,1],[1,0], s=500,marker="o", c="r")
line = plt.scatter(1.00,1.00, s=200,marker="o", c="b")
line2=plt.scatter(0.00,0.00, s=200,marker="o", c="b")
line3 = plt.scatter(0,1.00, s=400,marker="x", c="r")
line4=plt.scatter(1.00,0.00, s=400,marker="x", c="r")
line3.set_clip_on(False)
line2.set_clip_on(False)
line4.set_clip_on(False)
x1, y1 = [-0.2,0.8], [0.8, -0.2]

x2, y2 = [-0.2,1.5], [1.5, -0.2]

line5=plt.plot(x1, y1, x2, y2, clip_on = False,color="green")
plt.title("XOR: Klasifikimi i pamundur nga nje vije")
plt.show()

<Figure size 640x480 with 1 Axes>

In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a[4:]

array([5, 6])